[package]
name = "ironworker"
version = "0.1.0"
edition = "2021"

[dependencies]
md5 = "0.7.0"
reqwest = { version = "0.12.7", features = ["blocking"] }
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
